trigger:
  branches:
    include:
      - main
      - develop

stages:
  - stage: 'PS'
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: 'Analyze'
        steps:
          - template: 'analyze-arm.yaml'
